<?php
/**
 * @file
 * Enables choose to a random member for merge a pull request of one project.
 */

/**
 * Implements hook_help().
 */
function bot_pullreq_help($path, $arg) {
  // @TODO: Soon... Very soon...
}

/**
 * Implements hook_menu().
 */
function bot_pullreq_menu() {
  $items['bot/pullreq'] = array(
    'access arguments' => array('access bot'),
    'description' => "Browse all projects with their members.",
    'page callback' => 'bot_pullreq_results',
  );

  return $items;
}

/**
 * Browse all projects with their members.
 * @return render_array
 */
function bot_pullreq_results() {
  // @TODO: FINISH IT!!
  $rows = array();
  //return theme('table', $header, $rows, $table_attributes);
}

/**
 * Read conversations.
 * @param $data object with all information.
 * @param bool $from_query
 * @return int exit!
 */
function bot_pullreq_irc_msg_channel($data, $from_query = FALSE) {
  $to = empty($data->channel) ? $data->nick : $data->channel;
  $botdata["message"] = $data->messageex;
  $botdata["channel"] = empty($data->channel) ? "" : $data->channel;
  $botdata["nick"] = $data->nick;

  if (count($botdata["message"]) < 2) {
    return 0;
  }
  $pullreq = new PullReq();

  switch ($botdata["message"][0]) {
    case "addProject":
      $result = $pullreq->setProject($botdata);
      break;

    case "addMember":
      if (count($botdata["message"]) < 3) {
        return 0;
      }
      $result = $pullreq->setMember($botdata);
      break;

    case "delMember":
      if (count($botdata["message"]) < 3) {
        return 0;
      }
      $result = $pullreq->delMember($botdata);
      break;

    case "delProject":
      $result = $pullreq->delProject($botdata);
      break;

    case "getAllMembers":
      $result = $pullreq->getAllMembers($botdata);
      break;

    case "pullreq":
      $result = $pullreq->pullreq($botdata);
      break;

    default:
      return 0;
  }

  bot_message($to, $result["msg"]);

}

/**
 * Read query messages.
 * @param $data object with all information.
 */
function bot_pullreq_irc_msg_query($data) {
  bot_pullreq_irc_msg_channel($data, TRUE);
}
